### PR TITLE
Update quickstart step 2

### LINKED ISSUE #46: Quickstart suggests to create a directory
> Create a new directory, `unisoncode` (or any name you choose), then run the `ucm init` binary from within that directory. You'll see a note about "No codebase exists here so I'm initializing one..." and a welcome screen.

That's not what happens with the latest version.

1. There's no need to create a directory, `ucm init` will initialize a codebase in `$HOME/.unison`.
2. The output of `ucm init` is different.

### PR DESCRIPTION
**Pull request by int-index**
Closes #46

### CODE REVIEW

**Comment by aryairani** [comment]
Hey, thanks for fixing this.  It looks good although I’m a little hesitant about the `rm -rf` suggestion.  What do you think?

**Comment by int-index** [comment]
If there's a way to initialize/create something, there should be a way to remove it from the system. I'm mentioning `rm -rf` to clarify that Unison will not break if you do this, and there's no special command like `ucm clean` for this.

**Comment by aryairani** [comment]
I was thinking that Unison *would* break, in the sense that you are deleting all your code and work for potentially all projects.  There’s no `ucm clean` in the same way that my C compiler doesn’t have a command to delete all the C source on my system 😬 

.unison is more the aggregation of all your work, as opposed a place where Unison stashes some state or temp files that can be wiped out without consequences.

**Comment by int-index** [comment]
OK, I can see how this can be misleading. I meant that it wouldn't break in the technical sense, in that you wouldn't see any internal errors.

**Pull request merged**
