### PR TITLE
update docs with `match .. with` and `cases` syntax

### PR DESCRIPTION
**Pull request by anovstrup**
This PR updates the language reference and abilities tutorial to use the new `match .. with` and `cases` syntaxes. 

NOTE: This should not be merged to `production` until after the new syntax is included in an official release.

### CODE REVIEW

**Comment by aryairani** [comment]
@anovstrup Thanks for doing this!

Here's a funny thing I noticed, reading through the diff.  We added `cases` as a streamlined `case/of`, but at the same time, we renamed `case/of` to `match/with`.  So we have `match/with` and `cases`. Seems like an oversight.  😅

**Comment by aryairani** [comment]
@pchiusano

**Comment by aryairani** [comment]
@anovstrup Thanks for doing this!

Here's a funny thing I noticed, reading through the diff.  We added `cases` as a streamlined `case/of`, but at the same time, we renamed `case/of` to `match/with`.  So we have `match/with` and `cases`. Seems like an oversight.  😅 /cc @runarorama @pchiusano

**Comment by anovstrup** [comment]
@aryairani That was actually an intentional decision. See @pchiusano's reasoning here: https://github.com/unisonweb/unison/pull/1192#issuecomment-583640965. (The first implementation used `matches` and `match .. with`, but I agreed with Paul that `cases` reads better than `matches`: you `match` a scrutinee with a set of `cases`.)

**Comment by aryairani** [comment]
HMMMMM :)

What about just `match` ?

```unison
foo x = match x with
  [] -> "empty"
  _ -> "full"

foo = match
  [] -> "empty
  _ -> "full"
```

**Comment by aryairani** [comment]
@pchiusano

**Comment by anovstrup** [comment]
Maybe. Although parsing that might be difficult?

**Comment by pchiusano** [comment]
@aryairani yeah, this was deliberate... parsing not a slam dunk with using `match` to introduce... because the thing after `match` can now be either an expression (as in `match blah with`) or it can be a pattern. Except expressions and patterns overlap... like `x` is a valid pattern and expression... Maybe it's possible, but does not seem like a good idea / recipe for really poor error messages.

**Comment by aryairani** [comment]
@pchiusano Bummer, I was hoping it could be as simple as like 
```
"match" <vsemi> [cases]
```
vs 
```
"match" <expression> "with" <vsemi> [cases]
```
What even is a vsemi? :)

**Pull request merged**
