### PR TITLE
add tutorial on abilities to unisonweb.org/docs

### PR DESCRIPTION
**Pull request by atacratic**
This adds a tutorial on abilities to https://www.unisonweb.org/docs, after the language reference.

Am hoping people will think this suitable to merge as I've spent many hours on it!  If you have misgivings though, don't be shy to say so.

Thanks to those who answered my questions as I was learning this stuff myself...

### Exposure so far:
(in order of who replied first in my [slack thread](https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1566514153020200):)
- Mitchell Rosen has read some of it
- Dave Nicponski has read half
- Ben Fradet has read the whole thing (he says 'excellent stuff' :smile:), but was mostly already familiar with the material
- Brandon Barker is hoping to get round to reviewing it, but hasn't yet.
I got some feedback from them which led me to rejig the 'using abilities' section.  

Overall I think it's *not* yet had a thorough read from someone new to the material, with them taking careful notes about stuff that confuses them.  I will keep trying to arrange this, and submit edits that come out of that later.  

### Intended audience:
Unison newbies.  Functional programming 'developing beginners', who know their way round a function definition, its signature, and recursion.  Familiarity with Haskell not assumed.  Zero knowledge of effects/abilities assumed.  Slow pace, example-led.  No comparison drawn with alternative approaches; monads not mentioned.  

### Why spend so many words on abilities?
It's very novel, and there's precious little stuff on the web with the same intended audience as stated above - certainly not for systems similar to Unison's.  So makes sense we give it some early focus in documentation.  Hopefully in time we can do a similar treatment on other areas which are hard to learn by analogy with other languages - e.g. the codebase model.  

### Learning objective:
Get people to master abilities and handlers to the point they can do anything they want with them.  Supply all the language-technical info that could be relevant to them.  Motivate and build intuition through examples.  More detail on what the reader ends up knowing listed in conclusion.md.  

### Overall structure:
The basic idea behind the structure is that people will use abilities (i.e. make requests) sooner, and more frequently, than they invoke handlers for them; and they will invoke handlers sooner, and more frequently, than they write their own handlers.  So the order of exposition is: using abilities, invoking handlers, writing handlers.  This does mean that there's a heck of a lot of text to get through before the reader actually sees a handler for the first time.  But hey they can skip forward if they're impatient.  

There's are substantial detours through understanding all the finer points of how abilities work in type signatures, first during and then also after the 'using abilities' stuff.  I decided to cover all the intricacies and gotchas I was aware of.

### Notes:
- I have linked to open compiler bugs where they are things people might notice.
- There are exercises at the end.  They're only doable after people know how to write their own handlers, hence not interspersed with the tutorial itself.
- The examples are chosen to illustrate: messing with control flow by calling the continuation 0 or 2+ times; flow of information in to and out of the program; IO.
- I've tried to make the markdown and its links and headings look like that in the source for the language reference, but I haven't been able to see how it will actually render on the site.  Hopefully after it's merged to master there's a URL I can go look at to spot snags before it gets published.  

@pchiusano could you review, or nominate someone?  Maybe you don't need to do a detailed review and read the whole thing?

### CODE REVIEW

**Comment by atacratic** [comment]
Cool - I see there is a 'deploy preview' (currently at https://deploy-preview-26--unisonweb-org.netlify.com/docs/language-reference), but it looks pretty broken and I don't know why...  Sidebar extends beyond page footer, and sidebar links are broken.  I wonder if it's a limitation in the previewing system, or if there's something actually wrong.

**Comment by atacratic** [comment]
OK, who'd have thought, it was my mistake.  It looks better now, although there is still a glitch with the footer cutting through the sidebar when viewing shorter pages of documentation.  

I'll go through the deploy preview checking links and how things look, and report back here when that's done.

**Comment by pchiusano** [comment]
Hey @atacratic I still have only taken a brief look through this, but it’s looking pretty good and right now we have like no tutorial style docs of this so seems like a win. 😀 We may do a bunch of further editing of this after merge though, FYI, so don’t be alarmed by that.

Can you let us know when you think it is ready to go? You mentioned above that you were fixing some things.

**Comment by aryairani** [comment]
I didn't get too far, unfortunately, but here's some initial thoughts: https://gist.github.com/aryairani/76f543fb4357c1200094185492827189

**Comment by atacratic** [comment]
OK I think this is ready to merge now.  Thanks @aryairani for the comments.  I've added a new 'whistlestop tour' to the first page, which hopefully makes the motivation more comprehensible as well as giving people more of a framework to understand the rest of the material.

@pchiusano wants this to get an edit pass from someone at unison HQ - sounds good to me: shout if I should raise a ticket somewhere to track that.

**Comment by atacratic** [comment]
OK, it's even more ready now.

Also just a note to flag the motivation section as needing particular attention / a rewrite, as and when someone revisits this.

**Comment by atacratic** [comment]
OK I have finished fiddling with this now @pchiusano :slightly_smiling_face:

**Comment by aryairani** [comment]
Sorry for the mixed messages — I’d like to hold off on publishing this until we can do a more thorough edit. I don’t think there’s any rush and want peoples first exposure to this topic to be excellent.

**Comment by atacratic** [comment]
Ha, OK, no problem, edit away :+1:

**Comment by pchiusano** [comment]
@atacratic sorry for churn, but could you merge this back into a single file, and see if you can produce this from a transcript (which will also handle updating all the names to use suffix-based resolution)? I think that'll be more maintainable. If it's too annoying to do as a transcript, then you can skip that, but getting the names and output cleaned up  to match current Unison would be good.

The source of the transcript if you go that route can be checked in [here](https://github.com/unisonweb/unisonweb-org/tree/master/src/data/transcripts). We'll eventually have CI generate the output, for now I've been running the transcripts manually.

**Comment by atacratic** [comment]
Status update:
 - nearly ready, I just have another hour or so to spend, cleaning the transcript technicalities - planning on doing that on Wednesday
 - now updated with the new `handle x with h` syntax
 - requires [unison 1167](https://github.com/unisonweb/unison/pull/1167) to compile the transcript, as it now uses unison:hide:all fences.

FYI @pchiusano

**Comment by atacratic** [comment]
@pchiusano OK this is done!  Over to you to publish.  Hopefully it still fits into your plans.  Let me know if there's something I can do to make it fit better.

Note:
 - it requires [unison 1167](https://github.com/unisonweb/unison/pull/1167) (not yet merged) to compile the transcript, as it now uses unison:hide:all fences
 - I've checked how the output markdown renders as a gist ([here](https://gist.github.com/atacratic/c9cccabe1ff47498990b0742ec01c1b0)), but I couldn't work out how to make it appear in the deploy preview so haven't checked the final rendering (although I did check it previously before the transcript conversion).

**Comment by atacratic** [comment]
OK - the decision is that Paul is going to keep on with writing a new official tutorial for abilities (one that is a bunch shorter, for one thing!) and we'll demote this one to an 'unofficial' doc [here](https://gist.github.com/atacratic/7a91901d5535391910a2d34a2636a93c), which may or may not have any circulation.  That's fine with me (I got some good fun and learning out of writing it at least.)  I look forward to reading the official tutorial!

**Pull request closed without merging**
